version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    # Packet capture may require additional privileges/capabilities on Linux
    # Uncomment if needed:
    # cap_add:
    #   - NET_ADMIN
    #   - NET_RAW
    # network_mode: host
    # privileged: true
